

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    env_file:
      - .env

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
